version: '2.34.0-desktop.1'
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run pageObjects-firefox
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results